### DISCUSSION TITLE
Docker images also for elasticsearch and redis

### DISCUSSION THREAD

**Discussion by diebunten** [ICIJ/datashare#936] [General]
Hello! We try to install datashare on our web server in server mode. 
Our server administrator is stuck now. He writes: „In order to setup this they need to provide the docker images also for elasticsearch and redis so the docker run works properly.“ 
Can you advice us?

**Comment by pirhoo** [comment]
Hello,

If you are trying to user Datashare in SERVER mode, you also need to configure Redis and Elasticsearch servers. You can check out this repo with a full example:

https://github.com/ICIJ/datashare-keycloak-integration

There you will find a `docker-compose.yml` including the two services:

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    restart: on-failure
    volumes:
      - type: volume
        source: elasticsearchdata
        target: /usr/share/elasticsearch/data
        read_only: false
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "cluster.name=datashare"
      - "discovery.type=single-node"
      - "discovery.zen.minimum_master_nodes=1"
      - "xpack.license.self_generated.type=basic"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE"
    networks:
      intranet:

  redis:
    image: redis:4.0.1-alpine
    restart: on-failure
    networks:
      intranet:
```

Please note I changed the ElasticSearch version to 7.9.1, the latest one compatible with Datashare.
